#!/bin/bash

##############################################################################
# This file is part of RetroTink-Setup (https://github.com/xovox/RetroTink-Setup)
#
# RetroTink-Setup is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# RetroTink-Setup is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RetroTink-Setup.  If not, see <https://www.gnu.org/licenses/>.
##############################################################################

# change to ntsc or pal
# PAL IS CURRENTLY UNSUPPORTED
export tvRegion="ntsc"

# where we keep everything
export retroTinkDir="/home/pi/RetroTink-Setup"

# our per-system video modes
export hdmiTimingsDir=$retroTinkDir/hdmi_timings/$tvRegion

# keep ansible from creating ugly .retry files
export ANSIBLE_RETRY_FILES_ENABLED=0
