---

##############################################################################
# This file is part of RetroTink-Setup (https://github.com/xovox/RetroTink-Setup)
#
# RetroTink-Setup is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# RetroTink-Setup is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RetroTink-Setup.  If not, see <https://www.gnu.org/licenses/>.
##############################################################################

- hosts: all
  connection: local
  become: yes
  become_user: root

  handlers:

    - name: Restart Samba
      service:
        name: smbd
        state: restarted
      listen: "restart samba"

  pre_tasks:

    - name: "Finding Our TV Region"
      set_fact:
        tv_region: "{{ lookup('env', 'tvRegion') }}"

    - name: "Gather Video Output Configuration"
      set_fact:
        hdmi_timings: "{{ lookup('file', 'hdmi_timings/{{ tv_region }}/default') }}"

    - name: "Are we NTSC"
      set_fact:
        segasixteen: "genesis"
        segasixteenfull: "Genesis"
      when: tv_region == "ntsc"

    - name: "Are we PAL"
      set_fact:
        segasixteen: "megadrive"
        segasixteenfull: "Mega Drive"
      when: tv_region == "pal"

  tasks:

    # vfat doesn't like the standard Ansible backup extension
    - name: "Backup /boot/config.txt"
      copy:
        src: /boot/config.txt
        dest: /boot/config.txt.{{ansible_date_time.epoch}}

    - name: "Generate /boot/config.txt"
      template:
        src: templates/config.txt.j2
        dest: /boot/config.txt

    - name: "Generate EmulationStation Systems List"
      template:
        src: templates/es_systems.cfg.j2
        dest: /etc/emulationstation/es_systems.cfg
        backup: yes
        owner: root
        group: root
        mode: 644

    - name: "Copy RetroArch Configs"
      synchronize:
        src: configs/retropie/
        dest: /opt/retropie/configs/
        rsync_opts:
          - "--backup"
          - "--suffix .{{ansible_date_time.epoch}}"

    - name: "Copy RetroArch ROM Configs To fba"
      synchronize:
        src: configs/roms/
        dest: /home/pi/RetroPie/roms/fba/
        rsync_opts:
          - "--backup"
          - "--suffix .{{ansible_date_time.epoch}}"

    - name: "Copy RetroArch ROM Configs To arcade"
      synchronize:
        src: configs/roms/
        dest: /home/pi/RetroPie/roms/arcade/
        rsync_opts:
          - "--backup"
          - "--suffix .{{ansible_date_time.epoch}}"

    - name: "Copy RetroArch ROM Configs To mame-libretro"
      synchronize:
        src: configs/roms/
        dest: /home/pi/RetroPie/roms/mame-libretro/
        rsync_opts:
          - "--backup"
          - "--suffix .{{ansible_date_time.epoch}}"

    - name: "Disable RetroArch Notification Text"
      lineinfile:
        dest: /opt/retropie/configs/all/retroarch.cfg
        backup: yes
        regexp: '^video_font_enable ='
        line: 'video_font_enable = "false"'

    - name: "Create Save States Directories"
      shell: /usr/bin/find . -mindepth 1 -maxdepth 1 -type d -exec mkdir -p /home/pi/RetroPie/savestates/{} \;
      args:
        chdir: /home/pi/RetroPie/roms

    - name: "Create Save Files Directories"
      shell: /usr/bin/find . -mindepth 1 -maxdepth 1 -type d -exec mkdir -p /home/pi/RetroPie/savefiles/{} \;
      args:
        chdir: /home/pi/RetroPie/roms

    - name: "Fix Permissions On Save States Directories"
      file:
        path: /home/pi/RetroPie/savestates
        state: directory
        owner: pi
        group: pi
        recurse: yes

    - name: "Fix Permissions On Save Files Directories"
      file:
        path: /home/pi/RetroPie/savefiles
        state: directory
        owner: pi
        group: pi
        recurse: yes

    - name: "Add Save States/Files Shares To Samba"
      blockinfile:
        block: "{{ lookup('file', 'files/smb.conf') }}"
        dest: /etc/samba/smb.conf
        backup: yes
      notify: "restart samba"

    - name: "Install 240p Test Suite ROMs & ISOs"
      synchronize:
        src: files/roms/
        dest: /home/pi/RetroPie/roms/
        rsync_opts:
          - "--exclude README.md"

    - name: "Download Theme: Freeplay"
      git:
        repo: https://github.com/rxbrad/es-theme-freeplay
        dest: /etc/emulationstation/themes/Freeplay

    - name: "Download Theme: GBZ35"
      git:
        repo: https://github.com/rxbrad/es-theme-gbz35
        dest: /etc/emulationstation/themes/GBZ35

    - name: "Download Theme: GBZ35 Dark"
      git:
        repo: https://github.com/rxbrad/es-theme-gbz35-dark
        dest: /etc/emulationstation/themes/GBZ35-Dark

    - name: "Download Theme: TFT"
      git:
        repo: https://github.com/anthonycaccese/es-theme-tft
        dest: /etc/emulationstation/themes/TFT

    - name: "Download Theme: Art Book Pocket"
      git:
        repo: https://github.com/anthonycaccese/es-theme-art-book-pocket
        dest: /etc/emulationstation/themes/ArtBookPocket

    - name: "Download Theme: Picade"
      git:
        repo: https://github.com/anthonycaccese/es-theme-picade
        dest: /etc/emulationstation/themes/Picade
